version: "3.3"
services:
  source:
    image: localhost:5000/labs/ndsobc-microservice-dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes: 
    - ./source:/code
    working_dir: /code
    ports: 
    - 8080:80
    environment:
      - SINK_HOST=sink
  sink:
    image: localhost:5000/labs/ndsobc-microservice-dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes: 
    - ./sink:/code
    working_dir: /code
    ports: 
    - 8081:80
